const products = [
    {
      id: 1,
      name: 'No Weapon Formed Against Me Will Prosper',
      date: 2022,
      collection: "Black Dog",
      price: 3000,
      image: ['/images/endscene.jpg'],
      media: 'Graphite and marker on paper, digital collage',
      dimensions: "3x3ft",
      description: 'A piece part of the “Black Dog” series using the motif of the black dog to illustrate the absurdity of the loyalty of suffering in life.',
      hasViolence: true,
    },

    {
      id: 2,
      name: 'When the soul breaks through the confines of its mortal frame',
      date: 2021,
      collection: '',
      price: 12000,
      image: ['/images/nihilist.jpg', '/images/nihilist-1.jpg', '/images/nihilistwarm.jpg'],
      media: 'Graphite, acrylic, marker on paper, digital collage',
      dimensions: "24x18in",
      description: 'This piece portrays a dichotomy of selves, with the elder positioned in a taxi\'s front seat and the younger self in the back, illustrating the poignant tension between mortal physicality and intellectual aspirations. The older self, a symbol of the earthly constraints, confronts the youthful self wielding a silencer, embodying the ceaseless pursuit of transcending worldly limits. As the aged visage signifies the inherent boundaries of our existence, the younger self becomes a symbol of the relentless quest for enlightenment, showcasing the perpetual struggle to overcome the limitations of the physical realm and embrace the boundless realm of intellectual exploration.',
      
    },
    
    {
        id: 3,
        name: 'SAP(FORTHESOUL)',
        date: 2022,
        collection: '',
        price: 10000,
        image: ['/videos/SAP.mp4', '/images/SAP.JPG'],
        media: '3D model sculpture, PIR motion sensor, DFPlayer, SD card, jumper wires, arduino uno',
        dimensions: "9x10x4in",
        description: '"SAP(FORTHESOUL)" is a multimedia art piece conceived during my sophomore year at Parsons School of Design. Utilizing AutoCAD, I crafted a 3D sculpture inspired by African plaques. The sculpture incorporates Arduino technology, employing a PIR motion sensor and DFPlayer with an SD card, to dynamically generate speeches exploring existential and absurdist themes. The spoken words, a compilation of writings by Jean-Paul Sartre, Albert Camus, and my own alterations, are transformed into speech through text-to-speech software, creating an immersive and thought-provoking experience within the 9x10x4in dimensions of the artwork.',
        
      },

      {
        id: 4,
        name: 'The Paradox of the Absurdist',
        date: 2022,
        collection: '',
        price: 1000,
        image: ['/images/absurdist.jpg'],
        media: 'Oil on canvas, digital collage',
        dimensions: '2x3ft',
        description: '“The Paradox of the Absurdist” is a collage painting regarding absurdism; the belief that human exist in a purposeless, chaotic world. With this knowledge one has the choice to rebel or embrace what life gives us.',
        hasViolence: true,
      },

      {
        id: 5,
        name: 'Fortis Fortuna Adiuvat',
        date: 2022,
        collection: 'Black Dog',
        price: 1000,
        image: ['/images/angel.JPG'],
        media: 'Graphite on paper, digital collage',
        dimensions: '30x40in',
        description: 'A piece part of the “Black Dog” series using the motif of the black dog to illustrate the absurdity of the loyalty of suffering in life.',
        hasViolence: false,
      },

      {
        id: 6,
        name: 'Kirin',
        date: 2023,
        collection: '',
        price: 1000,
        image: ['/images/kirin.jpg'],
        media:'Graphic, charcoal and conte crayon on paper',
        dimensions: "18x24in",
        description: 'A custom drawing made in traditional Japanese tattoo style that pays tribute to the Japanese mythological creature, the Kirin.',
      
      },

      {
        id: 7,
        name: 'Divinity in Hollowness',
        date: 2024,
        collection: '',
        price: 10000,
        image: ['/images/skeleton.jpg'],
        media:'Graphic, charcoal and conte crayon on paper',
        dimensions: "18x24in",
        description: '"Divinity in Hollowness", finished in 2024, explores the convergence of life and death through a haunting portrayal of a zombie-angel hybrid with a radiant cross on its forehead and four arms – symbolizing the struggle for divinity amid the desolation of existence. Rendered in graphic, charcoal, and conte crayon on paper, the 18x24in piece captures a desolate scene of decay along an empty river, where a decaying figure is haunted by the otherworldly presence. This piece evokes themes of  accepting one\'s hollowness, confronting the loss of self, and seeking transcendence in the void, welcoming viewers to reflect on the intersection of spirituality and mortality.',
      },

      {
        id: 8,
        name: 'Solo/Sinnerman',
        date: 2021,
        collection: '',
        price: 1000,
        image: ['/images/solo-1.JPG'],
        media: "Graphite, marker, acrylic on paper",
        dimensions: '6x6in',
        description: 'This piece serves as a profound self-portrait reflecting my present state, employing bold lines to evoke a dark and somber atmosphere inspired by film noir aesthetics. Originating from a dream featuring a conversation with a figure reminiscent of Machiavelli, the piece delves into the dichotomy of being perceived as the \'good guy\' loved rather than feared. The dream\'s impact on my principles and character is encapsulated in the portrait, subtly alluding to Christianity and smoking as symbols of a cynical hero navigating the complexities of the world while staying true to personal principles, even acknowledging inherent flaws.',
      },

      {
        id: 9,
        name: 'L\'homme noir et le chat',
        date: 2019,
        collection: 'Le Noir',
        price: 1000,
        image: ['/images/blackcat.jpg'],
        media: "Acrylic and oil on paper",
        dimensions: "9x12in",
        description: '"L\'homme noir et le chat," created in 2019 with acrylic and oil on paper, measures 9x12 inches. This artwork explores the complexity of subtle racial undertones within societal dynamics. Through the juxtaposition of a black man in a ski mask and a black cat with human-like eyes, the painting prompts reflection on the dehumanizing gaze and the awkward interplay between the two subjects.',
      },

      {
        id: 10,
        name: 'The Amerikkkan Neighbor',
        date: 2021,
        collection: '',
        price: 12000,
        image: ['/images/Amerikkka.jpg'],
        media: 'Oil, acrylic, aluminum foil on canvas, digital collage',
        dimensions: '2x3ft',
        description: 'This multimedia piece envisions a fictional intrusion, placing a KKK member in my living room, drawing inspiration from Faith Ringgold\’s The American People Series: Die and Picasso\’s Guernica. It serves as a critical exploration of America\'s unsettling fixation on racism, depicting the stagnant progress in addressing racial issues. Developed over nearly a year, the painting captures the escalating violence against the black community, highlighting the numbing impact of media coverage and the persistent lack of accountability for oppressors. Amid senseless bloodshed, the piece prompts reflection on the motivations behind such acts, suggesting the need for understanding to address the ongoing cycle of violence.',
      },

      {
        id: 11,
        name: 'Smh, Bill, smh',
        date: 2019,
        collection: '',
        price: 50,
        image: ['/images/bill.jpg'],
        media: 'Collage on paper, digital editing',
        dimensions: '8.5x11in',
        description: '',
      },

      {
        id: 12,
        name: 'The Caped Woman',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/cloak.jpg'],
        media: 'Collage on paper, digital editing',
        dimensions: '8.5x11in',
        description: '',
      },

      {
        id: 13,
        name: 'FORESIGHT!',
        date: 2021,
        collection: '',
        price: 16000,
        image: ['/images/foresight.JPG', '/images/foresight-1.JPG', '/images/foresight-2.JPG', '/images/foresight-3.JPG', '/images/foresight-4.JPG'],
        media: 'Oil and digital collage',
        dimensions: '24x18in',
        description: 'In "FORESIGHT," the portrayal of myself on a payphone surrounded by black witch moths and observed by the Whooping Boy on the Three Legged Horse delves into the interconnectedness of cultural monsters and the values embedded in Jamaican folklore. Examining entities like the duppies, specifically the Three Legged Horse with its deadly pursuit and the Whooping Boy riding it, reveals how these monsters embody societal fears and cultural warnings. Through the symbolism of the black witch moth, considered a harbinger of death, the narrative unfolds to explore the essence of fear and its transformative impact on desires, illustrating the profound connection between fear, powerlessness, and the pursuit of self-sufficiency.',
      },

      {
        id: 14,
        name: 'Godspeed Cowboy',
        date: 2020,
        collection: '',
        price: 15000,
        image: ['/images/cowboy.jpg'],
        media: 'Oil, acrylic, collage, charcoal, and fabric on canvas',
        dimensions: "18x24in",
        description: 'The multimedia artwork portrays a moment between myself as a toddler and my father, drawing parallels between Western Americana Cowboy culture and my father\'s characteristics. Through the inclusion of black figures and religious symbolism, such as the rope acting as a halo, the piece reflects the empowerment and values instilled by my father within a cultural context often overlooked.',
      },

      {
        id: 15,
        name: 'The Painter & Consciousness',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/painter.JPG'],
        media: 'Collage on paper, digital',
        dimensions: '8.5x11in',
        description: '',
      },

      {
        id: 16,
        name: 'Transparent',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/wineglass.jpg'],
        media: 'Acrylic on paper',
        dimensions: '9x12in',
        description: '"Transparent," created in 2019, is an acrylic on paper artwork measuring 9x12 inches. This composition features a still life arrangement of a wine bottle, wine glass, and a candle, serving as a metaphorical exploration of emotional transparency. The delicate interplay of light and shadow in this piece mirrors the vulnerability and openness one experiences when embracing a transparent state of being, inviting viewers to reflect on the subtle nuances of human connection.',
      },

      {
        id: 17,
        name: 'Sunday Morning Cowboy',
        date: 2020,
        collection: '',
        price: 1000,
        image: ['/images/sunday.jpg'],
        media: 'Oil, acrylic, fabric on canvas, and digital collage',
        dimensions: '18x24in',
        description: 'The multimedia artwork portrays a moment between myself as a toddler and my mother, delving into themes of religion, family dynamics, culture, and shared history. Through the symbolism of the burning bush, the piece encapsulates my mother\'s profound belief in me, reminiscent of the biblical narrative of Moses leading the Israelites. Despite occasional miscommunication, represented through the fragmented style, the artwork emphasizes the enduring strength of our familial bond and the profound influence of our shared past on shaping our identities.',
      },

      {
        id: 18,
        name: 'I GOT MY REPARATIONS, BOUGHT MYSELF SOME JEWELRY!',
        date: 2020,
        collection: '',
        price: 7000,
        image: ['/images/reparations.JPG'],
        media: 'Acrylic, collage on canvas panel',
        dimensions: "9x9in",
        description: 'In this mix media piece, acrylic, oil and collage were used to illustrate a radical idea about reparations. There’s a concern in which one, who are reparations really for, two, what is being given as reparations, three, is it ever enough and four, what happens when reparations are distributed?',
      },

      {
        id: 19,
        name: 'Glitter will always make you feel better',
        date: 2019,
        collection: '',
        price: 7000,
        image: ['/images/glitter.jpg', '/images/glitter-1.jpg', '/images/glitter-2.jpg', '/images/glitter-3.jpg', '/images/glitter-4.JPG'],
        media: 'Acrylic, oil on canvas, digital',
        dimensions: "18x24in",
        description: 'The series of artworks unfolds a nuanced exploration of my relationship with art, deepening as one progresses through the swiped images. The initial painting symbolizes a surface-level connection, where art is depicted as a captivating figure that collaboratively engages and educates me about various facets of life. However, as the digital distortions intensify with each swipe, the perception of this relationship transforms, culminating in a visually evocative "bad trip," highlighting the complex and unpredictable nature inherent in any artist-art relationship.',
      },

      {
        id: 20,
        name: 'infinitum',
        date: 2019,
        collection: '',
        price: 2500,
        image: ['/images/infinitum.jpg'],
        media: 'Charcoal, marker, and acrylic on canvas',
        dimensions: "8x11in",
        description: 'In this mixed media piece, I explore the enigma of existence, shaping the figure with a line and geometric forms to convey a sense of hollowness and ambiguity. Mirrored shapes symbolize the dualities and intersections of life, prompting reflection on the uncertainties surrounding identity. By incorporating textures that evoke the vastness of space, the artwork delves into the unknown aspects of both ourselves and the universe, culminating in a thought-provoking representation of a subconscious holding a gun – a poignant inquiry into the fate of consciousness after death and the profound question of our finiteness.',
      },

      {
        id: 21,
        name: 'Anti',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/anti.jpg'],
        media: 'photography and digital print',
        dimensions: '8.5x11in',
        description: 'In "Anti," created in 2019 through the medium of photography and digital print with dimensions of 8.5x11 inches, I captured a poignant narrative surrounding substance abuse. The spilled pills serve as a visual metaphor for the scattered consequences of addiction, while the overlaid image of a bloody sink intensifies the raw and visceral impact, addressing the physical toll and personal struggle associated with substance misuse. This piece prompts reflection on the destructive nature of substance abuse and fosters a dialogue on the urgent need for empathy and support in combating this pervasive issue. Please note that this scene is entirely fabricated, serving as a cautionary tale rather than a depiction of reality.',
        hasViolence: true,
      
      },

      {
        id: 22,
        name: 'Explicit Print',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/beachside.JPG'],
        media: 'digital print',
        dimensions: '8.5x11in',
        description: '',
        hasViolence: true,
      },

      {
        id: 23,
        name: 'Easy Way Out',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/exit.JPG'],
        media: 'Photography and digital print',
        dimensions: '8.5x11in',
        description: '',
      },

      {
        id: 24,
        name: 'Seul-2',
        date: 2019,
        collection: 'Seul',
        price: 1000,
        image: ['/images/seul-2.JPG'],
        media: 'Photography and digital editing',
        dimensions: '18x24in',
        description: '',
      },

      {
        id: 25,
        name: 'Consciousness',
        date: 2019,
        collection: '',
        price: 2000,
        image: ['/images/swan.JPG'],
        media: 'Charcoal on paper, digital editing',
        dimensions: '8x8in',
        description: '',
      },

      {
        id: 26,
        name: 'Sunday Radio',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/radio.jpg'],
        media: 'Charcoal on paper, digital editing',
        dimensions: '8x8in',
        description: '',
      },
      {
        id: 27,
        name: 'Breathe Alone',
        date: 2019,
        collection: 'Seul',
        price: 1000,
        image: ['/images/seul-1.JPG'],
        media: 'Photography and digital editing',
        dimensions: '36x18in',
        description: '',
      },

      {
        id: 28,
        name: 'Contrasted Saturation',
        date: 2019,
        collection: '',
        price: 2000,
        image: ['/images/umbrella.jpg', '/images/complex.jpg', '/images/satflowers.jpg', '/images/foodtruck.jpg', '/images/virus.jpg', '/images/bandana.jpg', '/images/cortez.jpg'],
        media: 'Photography and digital print',
        dimensions: '36x18in',
        description: 'Through simple adjustments like increasing saturation and altering contrast, I transformed ordinary photos into striking, almost graphic-like images. By capturing everyday objects with a camera, I created abstract compositions, such as a flower appearing as dynamic lines on a black backdrop. Some photos evoke the appearance of microscopic organisms, yet they solely depict flowers, showcasing a fascinating transformation from one form to another.',
      },

      {
        id: 29,
        name: 'Sacred Heartz',
        date: 2023,
        collection: '',
        price: 5000,
        image: ['/images/sacred.JPG'],
        media: 'Photography and digital editing',
        dimensions: '48x18in',
        description: '"Sacred Heartz" explores themes of transformation and release through a collage of self-portraits juxtaposed with evocative text. Drawing from Christian symbolism such as the sacred heart and gothic imagery, alongside motifs like bullets and crows, the piece delves into the complexities of personal journeys. Through photography and digital editing, I invite viewers to contemplate the process of letting go and finding catharsis amidst the turmoil of existence.',
      },

      {
        id: 30,
        name: 'Subterranean Voyage',
        date: 2023,
        collection: '',
        price: 5000,
        image: ['/images/sub.JPG',],
        media: 'photography and digital editing',
        dimensions: '36x18in',
        description: '"Subterranean Voyage" intricately weaves layers of self-portraits and evocative text within its digital collage, inviting viewers to embark on a journey of introspection and self-discovery. Through the use of symbolic imagery—a black-out angle bearing a sword, a gothic staircase guarded by Cerberus, and a skeleton adorned with impaled swords—the piece delves into existential themes of individualism and the pursuit of authenticity. Drawing inspiration from literary works such as Fyodor Dostoevsky\'s \'Notes from Underground,\' the artwork resonates with echoes of the underground man\'s struggle for autonomy amidst societal constraints, subtly urging viewers to confront their own paths with courage and resilience.',
      },

      {
        id: 31,
        name: 'Chromed: SUDO RM -RF',
        date: 2023,
        collection: '',
        price: 5000,
        image: ['/images/chromed.JPG', '/images/chromedgreen.JPG', '/images/chromedred.JPG'],
        media: 'Photography and digital edit',
        dimensions: '24x24in',
        description: 'Chromed: SUDO RM -RF" explores the fusion of human and machine, presenting a vision of cybernetic augmentation. Through photography and digital editing, I transformed myself into a cybernetic being, embodying themes of technological integration and exploration. With text fragments like "CHROMED" and "hscking the mainframe access granted," alongside intricate code backgrounds, the piece invites viewers to ponder the intersection of humanity and technology within the digital realm',
      },
      {
        id: 32,
        name: 'Targeted',
        date: 2021,
        collection: '',
        price: 2000,
        image: ['/images/TROUBLE1.JPG'],
        media: 'Photography and digital collage edit',
        dimensions: '36x36in',
        description: '',
        hasViolence: true,
      },

      {
        id: 33,
        name: 'Sandra',
        date: 2021,
        collection: '',
        price: 2000,
        image: ['/images/sandra25.jpg'],
        media: 'Photography and digital collage edit',
        dimensions: '36x36in',
        description: '',
      },
      {
        id: 34,
        name: 'Self Portrait of the Solo',
        date: 2021,
        collection: '',
        price: 2000,
        image: ['/images/trippingme11.JPG'],
        media: 'Photography and digital edit',
        dimensions: '18x24in',
        description: '',
      },
      {
        id: 35,
        name: 'SOULO',
        date: 2021,
        collection: '',
        price: 2000,
        image: ['/images/soulo.jpg', '/images/soulowarm.jpg', '/images/soulored.jpg', '/images/souloyellow.jpg'],
        media: 'Photography and digital edit',
        dimensions: '36x36in',
        description: '',
      },

      {
        id: 36,
        name: 'Alone with nothing but faith',
        date: 2022,
        collection: '',
        price: 15000,
        image: ['/images/mene.jpg'],
        media: 'Graphite and collage on paper, digital collage edit',
        dimensions: '18x24in',
        description: '"Alone with nothing but faith" delves into the depths of surrealism, presenting a haunting self-portrait laden with symbolism. Through graphite, collage, and digital manipulation, the piece portrays the subject draped in a sheet, adorned with tattoos, clutching a cigarette and a cracked egg. Against the backdrop of a lighthouse marked with cryptic graffiti and a distorted American flag, a black dog observes from afar, while a grass maze leads to an ominous ocean horizon. This enigmatic composition invites viewers to contemplate themes of isolation, mortality, and the fragile interplay between faith and despair.',
      },

      {
        id: 37,
        name: 'The Absurdist Manifesto',
        date: 2022,
        collection: '',
        price: 20000,
        image: ['/images/FAM-13.jpg', '/images/FAM-increasedcontrast3.jpg', '/images/FAM-14.JPG'],
        media: 'Graphite and collage on paper, digital collage edit',
        dimensions: '36x18in',
        description: '',
      },

      {
        id: 38,
        name: 'RHAATID BRITIAN FI WI COLONIZA',
        date: 2020,
        collection: '',
        price: 8000,
        image: ['/images/RBFWC-0.JPG', '/images/RBFWC-1.JPG', '/images/RBFWC-2.JPG', '/images/RBFWC-3.JPG', '/images/RBFWC-4.JPG', '/images/RBFWC-5.JPG', '/images/RBFWC-6.JPG', '/images/RBFWC-7.JPG', '/images/RBFWC-8.JPG'],
        media: 'Digital collage edit',
        dimensions: '18x18in',
        description: '',
      },

      {
        id: 39,
        name: 'SOLO-02',
        date: 2020,
        collection: '',
        price: 4000,
        image: ['/images/SOLO-02-0.JPG', '/images/SOLO-02-1.jpg', '/images/SOLO-02-2.jpg'],
        media: 'Graphite, marker, collage on paper, digital collage edit',
        dimensions: '11x14in',
        description: '',
      },

      {
        id: 40,
        name: 'Uncurated Pledge',
        date: 2020,
        collection: '',
        price: 4000,
        image: ['/images/uncurated-1.JPG', '/images/uncurated-2.jpg'],
        media: 'Digital collage edit',
        dimensions: '10x10in',
        description: '',
      },

      {
        id: 41,
        name: 'Bruised',
        date: 2020,
        collection: '',
        price: 5000,
        image: ['/images/bruised.JPG'],
        media: 'Digital collage edit',
        dimensions: '10x10in',
        description: '',
      },

      {
        id: 42,
        name: 'Happiness Break',
        date: 2020,
        collection: '',
        price: 5000,
        image: ['/images/happy-red.JPG', '/images/happy-green.JPG' ],
        media: 'Digital edit',
        dimensions: '10x10in',
        description: '',
      },

      {
        id: 43,
        name: 'In the bleak midwinter',
        date: 2020,
        collection: '',
        price: 12000,
        image: ['/images/newark.jpg'],
        media: 'Photography print',
        dimensions: '12x16in',
        description: '',
      },

      {
        id: 44,
        name: 'OPIA!',
        date: 2019,
        collection: '',
        price: 100000,
        image: ['/videos/opia.mp4','/images/opia-1.jpg', '/images/opia-2.JPG'],
        media: 'Digital edit and video',
        dimensions: '16x16in',
        description: '"OPIA!" is a captivating exploration of the enigmatic intensity inherent in human gaze, encapsulating a sense of both invasiveness and vulnerability within its bold composition.',
      },

      {
        id: 45,
        name: 'Cigarette Butts',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/cig-2.JPG', '/images/cig-1.JPG', '/images/cig-3.JPG', '/images/cig-4.JPG'],
        media: 'Photography and digital edit',
        dimensions: '8.5x11in',
        description: '',
      },

      {
        id: 46,
        name: 'Ma Soeur',
        date: 2019,
        collection: '',
        price: 10000000000,
        image: ['/images/cubism.jpg'],
        media: 'Oil and acrylic on canvas',
        dimensions: '18x24in',
        description: '',
      },

      
      {
        id: 47,
        name: 'Haze',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/haze.jpg'],
        media: 'Photography',
        dimensions: '18x24in',
        description: '',
      },

      {
        id: 48,
        name: 'Untitled',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/brush.jpg'],
        media: 'Photography',
        dimensions: '18x24in',
        description: '',
      },

      {
        id: 49,
        name: 'Freestyle illustrations',
        date: 2019,
        collection: '',
        price: 100000,
        image: ['/images/ill-1.jpg', '/images/ill-2.jpg', '/images/ill-3.jpg', '/images/ill-4.jpg', '/images/ill-5.jpg', '/images/ill-6.jpg', '/images/ill-7.jpg'],
        media: 'Marker on paper',
        dimensions: '18x24in',
        description: '',
      },

      {
        id: 50,
        name: 'Self Awareness isn\'t Depression',
        date: 2019,
        collection: '',
        price: 100,
        image: ['/images/SD.jpg'],
        media: 'Graphite on paper',
        dimensions: '18x24in',
        description: '',
      },

      {
        id: 51,
        name: 'I be so confused I ain\'t hard to find/ Prophets',
        date: 2019,
        collection: '',
        price: 100000,
        image: ['/images/false.jpg'],
        media: 'Graphite on paper',
        dimensions: '18x24in',
        description: '"I be so confused I ain\'t hard to find/ Prophets" delves into the notion of belief systems and influences. Through graphite on paper, it explores the concept of following \'prophets\'—not necessarily divine figures, but anything that exerts influence. It prompts viewers to contemplate their own \'prophets\' and the forces that shape their beliefs and actions.',
      },

      {
        id: 52,
        name: 'When an Angel Lies',
        date: 2022,
        collection: 'Black Dog',
        price: 100000,
        image: ['/images/lies.jpg', '/images/lies-1.JPG', '/images/lies-2.JPG', '/images/lies-3.JPG', '/images/lies-4.JPG'],
        media: 'Graphite on paper',
        dimensions: '18x24in',
        description: 'A piece part of the “Black Dog” series using the motif of the black dog to illustrate the absurdity of the loyalty of suffering in life.',
      },

      {
        id: 53,
        name: 'Docs et la Fleur',
        date: 2019,
        collection: '',
        price: 100000,
        image: ['/images/docs.jpg'],
        media: 'Acrylic on canvas',
        dimensions: '18x24in',
        description: 'A still life of doc marten boots with a flower inside of a boot. ',
      },

      {
        id: 54,
        name: 'I\'m not so pretty to look at',
        date: 2019,
        collection: '',
        price: 100000,
        image: ['/images/alter.jpg'],
        media: 'Acrylic and graphite on paper',
        dimensions: '18x24in',
        description: '',
      },

      {
        id: 55,
        name: 'Bonds in the finite',
        date: 2021,
        collection: '',
        price: 5000,
        image: ['/images/g.jpg'],
        media: 'Graphite and charcoal on paper',
        dimensions: '18x24in',
        description: '"Bonds in the Finite" delves into the intricate dynamics of human relationships, portraying the overlapping complexities within the finite encounters individuals experience. Through graphite and charcoal on paper, the piece captures the essence of fleeting connections and the limited number of people one may meet in a lifetime. It invites contemplation on the depth and significance of each encounter within the vast tapestry of human interaction.',
      },

      {
        id: 56,
        name: 'The Decrepit\'s Grin',
        date: 2021,
        collection: '',
        price: 50000,
        image: ['/images/grin-1.JPG', '/images/grin-2.JPG', '/images/grin-3.JPG'],
        media: 'Electrical tape, resin teeth sculpture',
        dimensions: '9x8x12in',
        description: '',
      },

      {
        id: 57,
        name: 'Hedonistic Cynic',
        date: 2022,
        collection: 'Black Dog',
        price: 50000,
        image: ['/images/nightlife2.jpg'],
        media: 'Graphite on paper, digital edit',
        dimensions: '24x18in',
        description: 'A piece part of the “Black Dog” series using the motif of the black dog to illustrate the absurdity of the loyalty of suffering in life.',
      },

      {
        id: 58,
        name: 'Second Wind',
        date: 2023,
        collection: '',
        price: 0,
        image: ['/images/secondwind.jpg', '/images/secondwind-1.jpg', '/images/secondwind-2.jpg', '/images/secondwind-3.jpg', '/images/secondwind-4.jpg'],
        media: 'Website',
        dimensions: '',
        description: 'Second Wind, a full stack online community-based platform that provide resources, support, and employment for those impacted by the criminal justice system. As a project manager and backend engineer for Second Wind, I orchestrated a space that provides resources, support, and employment for those impacted by the criminal justice system. I leveraged Express, Node,js, SQL, Postgres, Postman, Knex.js to develop models, controllers, and routes for all tables in the database to enable seamless CRUD functionality for all requests in the database.',
      },

      {
        id: 59,
        name: 'CareerSpring Interest Finder',
        date: 2023,
        collection: '',
        price: 0,
        image: ['/images/careerspring.jpg', '/images/careerspring-1.jpg', '/images/careerspring-2.jpg', '/images/careerspring-3.jpg'],
        media: 'Website Development',
        dimensions: '',
        description: 'As a Developer Contractor, I’ve been instrumental in developing software like CareerSpring’s Career Interest Profiler by leveraging JavaScript, HTML & CSS. This custom career assessment tool seamlessly integrated into WordPress serves as a beacon for individuals exploring their professional paths. Through meticulous design, wireframing, and technical implementation, I created a tool that not only enhances user experience but aligns with long-term organizational goals. This tool, part of CareerSpring, serves as a beacon, guiding individuals towards careers that align with their interests.',
      },
      
      {
        id: 60,
        name: 'METVoyager',
        date: 2023,
        collection: '',
        price: 0,
        image: ['/images/metvoyager.jpg', '/images/metvoyager-1.jpg', '/images/metvoyager-2.jpg'],
        media: 'Website Development',
        dimensions: '',
        description: 'METVoyager is a web platform I developed that leverages the MET API, Javascript, HTML and CSS to deliver artwork recommendations based on search functionality or by selecting specific categories to generate art that matches. The platform also allows users to save and revisit favorite artworks in their own personal gallery.',
      },

      {
        id: 61,
        name: 'Chrome Abyss',
        date: 2022,
        collection: '',
        price: 17000,
        image: ['/images/abyss-1.JPG', '/images/abyss-2.JPG', '/images/abyss-3.JPG', '/images/abyss-4.JPG' ],
        media: 'Digital edit and photography',
        dimensions: '16x16in',
        description: '"Chrome Abyss" delves into the realm of cybernetic transformation through digital editing, presenting a futuristic self-portrait laden with symbolic text and imagery. With phrases like "Chrome Abyss" and "data leak," the piece navigates themes of self-discovery and the exploration of unknown territories within oneself. Through this fusion of human and machine, the artwork invites contemplation on the boundaries of identity and the journey towards self-understanding.',
      },

      {
        id: 62,
        name: 'Fade Away',
        date: 2022,
        collection: '',
        price: 15000,
        image: ['/images/abyss-5.JPG'],
        media: 'Digital edit',
        dimensions: '16x16in',
        description: '',
      },

      {
        id: 63,
        name: 'Apollo',
        date: 2019,
        collection: '',
        price: 15000,
        image: ['/images/apollo.jpg'],
        media: 'Graphite on paper',
        dimensions: '9x12in',
        description: 'Still life study of Apollo bust.',
      },

      {
        id: 64,
        name: 'Obokuri eeumi',
        date: 2021,
        collection: '',
        price: 15000,
        image: ['/images/thershold.JPG'],
        media: 'Photography and digital edit',
        dimensions: '12x12in',
        description: '',
      },

      {
        id: 65,
        name: 'The Name\'s Dan Solo: Ghost',
        date: 2021,
        collection: '',
        price: 15000,
        image: ['/images/dipt11.jpg'],
        media: 'Digital edit',
        dimensions: '12x12in',
        description: 'One half of a diptych of my ambivalence to isolation.',
      },

      {
        id: 66,
        name: 'The Name\'s Dan Solo: Refuge',
        date: 2021,
        collection: '',
        price: 15000,
        image: ['/images/dipt21.JPG'],
        media: 'Digital edit',
        dimensions: '12x12in',
        description: 'One half of a diptych of my ambivalence to isolation.',
      },

      {
        id: 67,
        name: 'Get you a Kangol',
        date: 2021,
        collection: '',
        price: 150000,
        image: ['/images/kangol.JPG', '/images/kangol-1.JPG' ],
        media: 'Wire, aluminum foil, and plaster cloth sculpture',
        dimensions: '12x12in',
        description: 'A sculpture that pay homage to Kangols for its large impact and usage in black culture.',
      },

      {
        id: 68,
        name: 'Smoker\'s Delight',
        date: 2020,
        collection: '',
        price: 150000,
        image: ['/images/lighter.JPG' ],
        media: 'Photography and digital print',
        dimensions: '24x19in',
        description: '"The Smoker\’s Delight, 2020" captures the passage of time through a series of images depicting a Bic lighter\'s diminishing flame. Through photography, I explore the concept of time as a linear progression, with each frame frozen in a moment yet collectively forming the continuum of time. This piece invites viewers to contemplate the resilience of the eternal flame against the backdrop of temporal transience.',
      },

      {
        id: 69,
        name: 'PEACHFUZZ!',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/lips.jpg' ],
        media: 'Oil on panel',
        dimensions: '14x14in',
        description: 'An observational oil painting of my mouth.',
      },

      {
        id: 70,
        name: 'Cat Azz',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/cat-1.JPG', '/images/cat-1.5.jpg', '/images/cat-2.jpg', '/images/cat-3.jpg', '/images/cat-4.JPG'],
        media: 'Graphite, markers on paper',
        dimensions: '8.5x11in',
        description: 'A short comic, about a cat named Lou who doesn\'t give a cat\'s ass about anything.',
      },

      {
        id: 71,
        name: 'Death of a Rasta',
        date: 2022,
        collection: '',
        price: 250000,
        image: ['/videos/rip.mp4'],
        media: 'Found media, fire, acrylic, charcoal, and charcoal on cardboard, video',
        dimensions: '46x34in',
        description: '',
      },

      {
        id: 72,
        name: 'SOLO',
        date: 2021,
        collection: '',
        price: 250000,
        image: ['/images/so-1.JPG','/images/so-2.JPG', '/images/so-2.JPG'],
        media: 'Spray paint on panel',
        dimensions: '24x18in',
        description: '',
      },

      {
        id: 73,
        name: 'Huh...What...Say that again...Sorry',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/deaf-1.jpg','/images/deaf-2.jpg', '/images/deaf-3.jpg', '/images/deaf-4.jpg', '/images/deaf-5.jpg', '/images/deaf-6.jpg'],
        media: 'Wired Sculpture',
        dimensions: '',
        description: '"Huh...What...Say that again...Sorry" is a wired sculpture that challenges perceptions of truth and interpretation. By distorting the face and placing the ear far from its usual position, it prompts viewers to reconsider their understanding of reality and the authority of interpretation. Through this exploration, it highlights the nuanced complexities of communication and the profound impact of individual perspectives.',
      },

      {
        id: 74,
        name: 'Overlooker',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/whit-1.JPG','/images/whit-2.JPG', '/images/whit-3.JPG'],
        media: 'Photography and digital editing',
        dimensions: '',
        description: '',
      },

      {
        id: 75,
        name: 'Overcast Character Designs',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/overcast-1.JPG','/images/overcast-2.JPG', '/images/overcast-3.JPG'],
        media: 'Graphite, marker and digital editing',
        dimensions: '',
        description: '',
      },

      {
        id: 76,
        name: 'High Fashion?',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/durag-1.JPG','/images/durag-3.JPG','/images/durag-2.JPG' , '/images/durag-4.jpg'],
        media: 'Graphite, soft pastel and digital editing',
        dimensions: '8.5x11in',
        description: 'A piece that critiques the high end fashion world for consistent discrediting and misuse of black culture.',
      },

      {
        id: 78,
        name: 'An ambigious trip, enjoy',
        date: 2020,
        collection: '',
        price: 250000,
        image: ['/videos/ambigious.mp4'],
        media: 'Film and video editting',
        dimensions: '',
        description: '',
      },

      {
        id: 79,
        name: 'Human [Club]',
        date: 2020,
        collection: '',
        price: 250000,
        image: ['/videos/humanclub.mp4'],
        media: 'Film and video editting',
        dimensions: '',
        description: '',
      },

      {
        id: 80,
        name: 'Sankofa & Enso',
        date: 2020,
        collection: '',
        price: 250000,
        image: ['/images/sankofa.jpg'],
        media: 'Digital editting',
        dimensions: '9x9in',
        description: '',
      },

      {
        id: 81,
        name: 'Gradient',
        date: 2020,
        collection: '',
        price: 250000,
        image: ['/images/gradient.jpg'],
        media: 'collage on paper',
        dimensions: '12x12in',
        description: '',
      },

      {
        id: 82,
        name: 'Stars in glass',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/starry.jpg'],
        media: 'Photography',
        dimensions: '',
        description: '',
      },

      {
        id: 83,
        name: 'To be like them',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/etre.JPG'],
        media: 'Photography and digital editing',
        dimensions: '',
        description: '"To be like them" captures a visceral moment in a staged scene, prompting reflection on the perils of sacrificing oneself for societal ideals. Through photography and digital editing, the piece delves into the complexities of individual identity and societal pressures. Please note that this scene is entirely fabricated, serving as a cautionary tale rather than a depiction of reality.',
        hasViolence: true,
      },

      {
        id: 84,
        name: 'Digital Mandalas',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/digitalflower.JPG', '/images/digitalflower-1.JPG', '/images/digitalflower-2.JPG', '/images/digitalflower-3.JPG', '/images/digitalflower-5.JPG', '/images/digitalflower-6.JPG', '/images/digitalflower-7.JPG', '/images/digitalflower-8.JPG'],
        media: 'Digital editing',
        dimensions: '',
        description: '',
      },

      {
        id: 85,
        name: 'When I see this I think of home',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/bk.jpg'],
        media: 'Photography',
        dimensions: '',
        description: '',
      },

      {
        id: 86,
        name: 'Au revior',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/au-1.jpg','/images/au-7.jpg', '/images/au-2.jpg', '/images/au-3.jpg', '/images/au-4.jpg','/images/au-6.jpg', '/images/au-8.jpg' ],
        media: 'Photography',
        dimensions: '',
        description: '"Au Revoir" encapsulates my farewell to New York through a series of hazy, moving-camera photographs, reflecting the blurred lines of memory. By desaturating colors, I evoke the somber emotions of departure, highlighting the fleeting nature of time and the ever-changing concept of home. Through this work, I explore the complex emotions of moving on and the realization that home is ultimately a reflection of personal experience.',
      },

      {
        id: 87,
        name: 'COZI',
        date: 2018,
        collection: '',
        price: 250000,
        image: ['/images/cozi-1.JPG', '/images/cozi-2.JPG', '/images/cozi-4.JPG', '/images/cozi-3.JPG', '/images/cozi-5.jpg'],
        media: 'Digital art',
        dimensions: '',
        description: '',
      },

      {
        id: 88,
        name: 'Cash Rules',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/cashrules.jpg'],
        media: 'Digital editing',
        dimensions: '',
        description: '',
      },

      {
        id: 89,
        name: 'Still Nega',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/still.jpg'],
        media: 'Acrylic and oil on canvas',
        dimensions: '',
        description: '',
      },

      {
        id: 90,
        name: 'Untitled Self Portrait',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/self.jpg'],
        media: 'Acrylic on canvas',
        dimensions: '',
        description: '',
      },

      {
        id: 91,
        name: 'Untitled',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/fire-1.jpg', '/images/fire-2.jpg', '/images/fire-3.jpg'],
        media: 'Digtial art',
        dimensions: '',
        description: '',
      },

      {
        id: 92,
        name: 'Untitled',
        date: 2019,
        collection: '',
        price: 250000,
        image: ['/images/noir-haze.JPG'],
        media: 'Photography',
        dimensions: '',
        description: '',
      },

      {
        id: 93,
        name: 'Tattoos on fake skin',
        date: 2024,
        collection: '',
        price: 250000,
        image: ['/images/tat-6.jpg', '/images/tat-4.jpg', '/images/tat-7.jpg', '/images/tat-5.jpg'],
        media: 'Tattoo on fake skin',
        dimensions: '',
        description: '',
      },

      {
        id: 94,
        name: 'Flash Designs for Tattoos',
        date: 2024,
        collection: '',
        price: 250000,
        image: ['/images/tat-1.jpg','/images/tat-2.jpg', '/images/tat-3.jpg'],
        media: 'Graphite and marker on paper',
        dimensions: '',
        description: '',
      },

      {
        id: 95,
        name: 'Theoria mutantium',
        date: 2024,
        collection: '',
        price: 250000,
        image: ['/images/mutant-1.JPG','/images/mutant-2.JPG', '/images/mutant-3.JPG', '/images/mutant-4.jpg'],
        media: 'Photography and digital edit',
        dimensions: '',
        description: '',
      },

      {
        id: 96,
        name: 'Early works',
        date: 2018,
        collection: '',
        price: 250000,
        image: ['/images/oldie-1.JPG'],
        media: 'Digital art',
        dimensions: '',
        description: '',
      },

      {
        id: 97,
        name: 'Early works',
        date: 2018,
        collection: '',
        price: 250000,
        image: ['/images/oldie-2.JPG'],
        media: 'Digital art',
        dimensions: '',
        description: '',
        hasViolence: true,
      },

      {
        id: 98,
        name: 'Motion Heat Cutter/ Gluttony',
        date: 2021,
        collection: '',
        price: 250000,
        image: ['/images/heatcutter-2.jpg', '/images/heatcutter-1.jpg', '/images/heatcutter-4.jpg', '/images/heatcutter-3.jpg'],
        media: '3D model sculpture, 5V relay, nichrome wire, 9V battery, arduino board, tilt ball switch, foam',
        dimensions: '',
        description: '"Motion Heat Cutter" is a 3D model sculpture integrating motion detection to activate a nichrome wire that burns at 400 degrees fahrenheit through a tilt ball switch. This interactive tool, allowing users to rotate it 90 degrees, was crafted with the purpose of sculpting a foam representation critiquing the gluttony of the TransAtlantic Slave trade and the exploitation of black labor in sugar production. By juxtaposing foam with sugar as materials, the piece unveils the hidden exploitative nature underlying the commodification of sugar, urging contemplation on the complexities of industrialization and exploitation within our societal structures.',
      },

      
  ];
  
  export default products;